-- [nfnl] Compiled from fnl/saenkomm/plugins-configs/ranger.fnl by https://github.com/Olical/nfnl, do not edit.
module(dotfiles.plugins.ranger, {[require] = {[utils] = saenkomm.util}})
__fnl_global__def_2d(float2nr, vim.fn.float2nr)
__fnl_global__def_2d(round, vim.fn.round)
utils["set-var"]("g", "rnvimr_enable_picker", 1)
utils["set-var"]("g", "rnvimr_enable_ex", 1)
utils["set-var"]("g", "rnvimr_enable_bw", 1)
utils["set-var"]("g", "rnvimr_vanila", 1)
utils["set-var"]("g", "rnvimr_action", {["<c-x>"] = "NvimEdit split false", ["<c-v>"] = "NvimEdit vsplit false", ["<c-e>"] = "NvimEdit edit", gw = "JumpNvimCwd"})
utils["set-var"]("g", "rnvimr_presets", {{width = 0.9, height = 0.9}})
return utils.noremap("n", "<c-n>", ":RnvimrToggle<cr>")
