require 'settings.plugins.airline'
require 'settings.plugins.asyncrun'
require 'settings.plugins.completion-nvim'
require 'settings.plugins.easymotion'
require 'settings.plugins.indentline'
require 'settings.plugins.limelight'
require 'settings.plugins.lsp-saga'
require 'settings.plugins.nerdcommenter'
require 'settings.plugins.nvim-treesitter'
require 'settings.plugins.ranger'
-- require 'settings.plugins.telescope'
require 'settings.plugins.vim-better-whitespace'
require 'settings.plugins.vim-floaterm'
require 'settings.plugins.vim-illuminate'
require 'settings.plugins.vim-rooter'
require 'settings.plugins.vim-startify'
