(module saenkomm.lsp.lspkind)

(def menu_icons {:path     " [path]"
                 :vsnip    " [snip]"
                 :luasnip  " [snip]"
                 :nvim_lsp " [lsp]"
                 :nvim_lua " [lsp]"
                 :conjure  " [conj]"
                 :buffer   " [buf]"
                 :omni     "𐂷 [omni]"
                 :Copilot  " [copilot]"})

(def menu_kind {:Text          "  [text]"
                :Method        " [method]"
                :Function      " [function]"
                :Constructor   " [constructor]"
                :Field         "ﰠ [field]"
                :Variable      " [variable]"
                :Class         " [class]"
                :Interface     " [interface]"
                :Module        " [module]"
                :Property      " [property]"
                :Unit          " [unit]"
                :Value         " [value]"
                :Enum          " [enum]"
                :Keyword       " [key]"
                :Snippet       " [snippet]"
                :Color         " [color]"
                :File          " [file]"
                :Reference     " [reference]"
                :Folder        " [folder]"
                :EnumMember    " [enum member]"
                :Constant      " [constant]"
                :Struct        " [struct]"
                :Event         "⌘ [event]"
                :Operator      " [operator]"
                :TypeParameter "⌂ [type]"
                :Copilot       " [copilot]"})
