vim.g.mapleader = ' '
vim.g.maplocalleader = ','

require 'mappings.common'
require 'mappings.buffers'
require 'mappings.easy-align'
require 'mappings.easymotion'
require 'mappings.clever-f'
require 'mappings.fzf'
require 'mappings.git'
require 'mappings.limelight'
require 'mappings.nerdcommenter'
require 'mappings.obvious-resize'
require 'mappings.ranger'
require 'mappings.vim-test'
require 'mappings.nvim-tree'
